HAI ME TEH FUNCSHUN MAIN
	I HAS A VARIABLE TESTING TEH STRIN ITZ "hi"
	VISIBLE IN STDIO WIT "hi"

	I HAS A VARIABLE ABC TEH INTEGR ITZ CEIL IN MATH WIT 3.5
	VISIBLE IN STDIO WIT ABC
	BTW GIVEZ UP
	I HAS A VARIABLE A TEH INTEGR ITZ fibonacci IN TEST WIT 13
	VISIBLE IN STDIO WIT A
	VISIBLE IN STDIO WIT NAO IN TIEM MOAR 5 LES 10
	VISIBLE IN STDIO WIT NAO IN TIEM
	BTW GIVEZ UP
	I HAS A VARIABLE B TEH DATE ITZ NEW DATE IN TIEM
	VISIBLE IN STDIO WIT GIMMEH IN B
	VISIBLE IN STDIO WIT NAO IN B

	BTW A ITZ fibonacci WIT 20
	I HAS A VARIABLE C TEH DATE ITZ NEW DATE IN TIEM
	NAO IN C
	I HAS A VARIABLE D TEH BOOL ITZ BEFORE IN C WIT B
	VISIBLE IN STDIO WIT D
KTHXBAI

HAI ME TEH VARIABLE OB TEH MAHCLAS ITZ NEW MAHCLAS

HAI ME TEH VARIABLE VAR TEH BOOL

HAI ME TEH LOCKD VARIABLE VAR3 TEH STRIN ITZ "\"HELLO\""

HAI ME TEH FUNCSHUN FUNC1 TEH BOOL WIT ARG1 TEH STRIN AN WIT ARG2 TEH BOOL
	VISIBLE IN STDIO WIT ARG1
	GIVEZ YEZ AN ARG2
KTHXBAI

HAI ME TEH FUNCSHUN FUNC2

KTHXBAI

HAI ME TEH FUNCSHUN FUNC3 TEH BOOL
	GIVEZ NO
KTHXBAI

HAI ME TEH FUNCSHUN fibonacci TEH INTEGR WIT N TEH NUMBR
	IZ N SMALLR THAN 3?
		GIVEZ 1
	KTHX

	I HAS A VARIABLE A TEH INTEGR ITZ fibonacci WIT N LES 1
	GIVEZ A MOAR fibonacci WIT N LES 2
KTHXBAI

HAI ME TEH LOCKD VARIABLE VAR2 TEH INTEGR

HAI ME TEH FUNCSHUN FUNC4 WIT ARG1 TEH BOOL
	GIVEZ YEZ
KTHXBAI

HAI ME TEH CLAS MAHCLAS
EVRYONE
	DIS TEH VARIABLE VAR TEH BOOL
	DIS TEH LOCKD VARIABLE VAR2 TEH INTEGR ITZ 50
	DIS TEH SHARD VARIABLE VAR3 TEH STRIN ITZ "hi ME A VAR"
	DIS TEH LOCKD SHARD VARIABLE VAR4 TEH DUBBLE ITZ 53

	DIS TEH FUNCSHUN FUNC1 TEH DUBBLE
	KTHX

	DIS TEH FUNCSHUN FUNNY TEH BOOL WIT ARG TEH MAHCLAS
		IZ YEZ?
			GIVEZ NO
		KTHX
	KTHX

	DIS TEH SHARD FUNCSHUN FUNC2 TEH DUBBLE
	KTHX
MAHSELF
	DIS TEH VARIABLE VAR33 TEH INTEGR
	DIS TEH LOCKD VARIABLE VAR22 TEH DUBBLE
	DIS TEH LOCKD SHARD VARIABLE SDLFKS TEH STRIN ITZ "NOPE"
	DIS TEH LOCKD SHARD VARIABLE DFJDJ TEH MAHCLAS ITZ NEW MAHCLAS
	DIS TEH VARIABLE JJ TEH MAHCLAS ITZ NEW MAHCLAS

	DIS TEH SHARD FUNCSHUN FUNC TEH BOOL WIT ARG12 TEH STRIN AN WIT ARG TEH BOOL
		IZ YEZ?
			GIVEZ NO
		KTHX
	KTHX
KTHXBAI
