I CAN HAS STDIO? MATH

HAI ME TEH VARIABLE VAR TEH BOOL

HAI ME TEH LOCKD VARIABLE VAR3 TEH STRIN ITZ "\"HELLO\""

HAI ME TEH FUNCSHUN FUNC1 TEH BOOL WIT ARG1 TEH STRIN AN WIT ARG2 TEH BOOL
	VISIBLE WIT VAR3
	GIVEZ YEZ AN NO
KTHXBAI

HAI ME TEH FUNCSHUN FUNC2

KTHXBAI

HAI ME TEH FUNCSHUN FUNC3 TEH BOOL
	GIVEZ NO
KTHXBAI

HAI ME TEH LOCKD VARIABLE VAR2 TEH INTEGR

HAI ME TEH FUNCSHUN FUNC4 WIT ARG1 TEH BOOL
	GIVEZ YEZ
KTHXBAI

HAI ME TEH CLAS MAHCLAS
EVRYONE
	DIS TEH VARIABLE VAR TEH BOOL
	DIS TEH LOCKD VARIABLE VAR2 TEH INTEGR ITZ 50
	DIS TEH SHARD VARIABLE VAR3 TEH STRIN ITZ "HI ME A VAR"
	DIS TEH LOCKD SHARD VARIABLE VAR4 TEH DUBBLE ITZ 53
	
	DIS TEH FUNCSHUN FUNC1 TEH DUBBLE
	KTHX
	
	DIS TEH SHARD FUNCSHUN FUNC2 TEH DUBBLE
	KTHX
MAHSELF
	DIS TEH VARIABLE VAR33 TEH INTEGR
	DIS TEH LOCKD VARIABLE VAR22 TEH DUBBLE
	DIS TEH LOCKD SHARD VARIABLE SDLFKS TEH STRIN ITZ "NOPE"
	
	DIS TEH SHARD FUNCSHUN FUNC TEH BOOL WIT ARG12 TEH STRIN AN WIT ARG TEH BOOL
		IZ YEZ?
			GIVEZ NO
		KTHX
	KTHX
KTHXBAI