HAI ME TEH FUNCSHUN MAIN TEH BOOL
	I HAS A VARIABLE V TEH MAHCLAS ITZ NEW MAHCLAS
	V ITZ NEW MAHCLAS
	FUNC1 WIT "HI" AN WIT YEZ
	FUNC1 WIT VAR3 AN WIT NO
	I HAS A VARIABLE Y TEH BOOL ITZ FUNNY IN V WIT V
	
	WHILE YEZ
		GIVEZ Y AN FUNNY IN V WIT V
	KTHX
KTHXBAI

HAI ME TEH VARIABLE OB TEH MAHCLAS ITZ NEW MAHCLAS

HAI ME TEH VARIABLE VAR TEH BOOL

HAI ME TEH LOCKD VARIABLE VAR3 TEH STRIN ITZ "\"HELLO\""

HAI ME TEH FUNCSHUN FUNC1 TEH BOOL WIT ARG1 TEH STRIN AN WIT ARG2 TEH BOOL
	VISIBLE IN STDIO WIT ARG1
	GIVEZ YEZ AN ARG2
KTHXBAI

HAI ME TEH FUNCSHUN FUNC2

KTHXBAI

HAI ME TEH FUNCSHUN FUNC3 TEH BOOL
	GIVEZ NO
KTHXBAI

HAI ME TEH FUNCSHUN FIBONACCI TEH INTEGR WIT N TEH INTEGR
	IZ N SMALLR THAN 3?
		GIVEZ 1
	KTHX
	
	I HAS A VARIABLE A TEH INTEGR ITZ FIBONACCI WIT N LES 1
	GIVEZ A MOAR FIBONACCI WIT N LES 2
KTHXBAI

HAI ME TEH LOCKD VARIABLE VAR2 TEH INTEGR

HAI ME TEH FUNCSHUN FUNC4 WIT ARG1 TEH BOOL
	GIVEZ YEZ
KTHXBAI

HAI ME TEH CLAS MAHCLAS
EVRYONE
	DIS TEH VARIABLE VAR TEH BOOL
	DIS TEH LOCKD VARIABLE VAR2 TEH INTEGR ITZ 50
	DIS TEH SHARD VARIABLE VAR3 TEH STRIN ITZ "HI ME A VAR"
	DIS TEH LOCKD SHARD VARIABLE VAR4 TEH DUBBLE ITZ 53
	
	DIS TEH FUNCSHUN FUNC1 TEH DUBBLE
	KTHX
	
	DIS TEH FUNCSHUN FUNNY TEH BOOL WIT ARG TEH MAHCLAS
		IZ YEZ?
			GIVEZ NO
		KTHX
	KTHX
	
	DIS TEH SHARD FUNCSHUN FUNC2 TEH DUBBLE
	KTHX
MAHSELF
	DIS TEH VARIABLE VAR33 TEH INTEGR
	DIS TEH LOCKD VARIABLE VAR22 TEH DUBBLE
	DIS TEH LOCKD SHARD VARIABLE SDLFKS TEH STRIN ITZ "NOPE"
	DIS TEH LOCKD SHARD VARIABLE DFJDJ TEH MAHCLAS ITZ NEW MAHCLAS
	DIS TEH VARIABLE JJ TEH MAHCLAS ITZ NEW MAHCLAS
	
	DIS TEH SHARD FUNCSHUN FUNC TEH BOOL WIT ARG12 TEH STRIN AN WIT ARG TEH BOOL
		IZ YEZ?
			GIVEZ NO
		KTHX
	KTHX
KTHXBAI