HAI ME TEH NATIV FUNCSHUN NAO TEH INTEGR

HAI ME TEH CLAS DATE
EVRYONE
	DIS TEH FUNCSHUN NAO TEH INTEGR
		TIME ITZ NAO IN TIEM
		GIVEZ TIME
	KTHX
	
	DIS TEH FUNCSHUN GIMMEH TEH INTEGR
		GIVEZ TIME
	KTHX
	
	DIS TEH FUNCSHUN SET WIT VALUE TEH INTEGR
		TIME ITZ VALUE
	KTHX
	
	DIS TEH FUNCSHUN BEFORE TEH BOOL WIT OTHER TEH DATE
		GIVEZ TIME SMALLR THAN TIME IN OTHER
	KTHX
MAHSELF
	DIS TEH VARIABLE TIME TEH INTEGR ITZ 0
KTHXBAI